.read lab13.sql

CREATE TABLE sp17favnum AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE sp17favpets AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE su17favpets AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE su17dog AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE su17alldogs AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE obedienceimage AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";

CREATE TABLE smallest_int_count AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";
